# instance_url should be Plextrac instance URL i.e. https://example.plextrac.com
instance_url: 
username: 
password: 

# example 2.6.0
api_version: 

prism_xlsx_file_path: 

# name of a report template in the Plextrac instance will be added to all reports
report_template_name: 
# name of a finding layout in the Plextrac instance will be added to all reports
findings_layout_name: 
